import { microgreenVarieties } from "@/lib/microgreenVarieties";
import type { ProductView } from "./types";

const microgreenTrayProducts: ProductView[] = microgreenVarieties.map((variety, index) => ({
  id: variety.productId,
  name: `${variety.name} Microgreens Tray`,
  description: variety.description,
  priceCents: variety.priceCents,
  kind: "ONE_TIME",
  subscriptionInterval: null,
  leadTimeDays: variety.leadTimeDays,
  cutoffNote: "One-time microgreens tray.",
  isAvailable: true,
  isFeatured: true,
  stockQuantity: null,
  weeklyCapacity: null,
  fulfillmentMode: "PICKUP",
  imageUrl: variety.image,
  imageS3Key: null,
  stripeProductId: null,
  stripePriceId: null,
  stripePriceAmountCents: null,
  sortOrder: 110 + index,
}));

export const fallbackProducts: ProductView[] = [
  {
    id: "small-weekly-greens",
    name: "Small Weekly Greens",
    description: "A simple weekly greens box for one person or light use.",
    priceCents: 1200,
    kind: "SUBSCRIPTION",
    subscriptionInterval: "WEEK",
    leadTimeDays: 7,
    cutoffNote: "Weekly tray count can be adjusted with the farm.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: null,
    weeklyCapacity: null,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 10,
  },
  {
    id: "medium-weekly-greens",
    name: "Medium Weekly Greens",
    description: "A practical weekly supply for salads, sandwiches, bowls, and garnish.",
    priceCents: 2000,
    kind: "SUBSCRIPTION",
    subscriptionInterval: "WEEK",
    leadTimeDays: 7,
    cutoffNote: "Weekly tray count can be adjusted with the farm.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: null,
    weeklyCapacity: null,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 20,
  },
  {
    id: "family-weekly-greens",
    name: "Family Weekly Greens",
    description: "A larger weekly harvest for families, meal prep, or serious microgreens use.",
    priceCents: 3200,
    kind: "SUBSCRIPTION",
    subscriptionInterval: "WEEK",
    leadTimeDays: 7,
    cutoffNote: "Weekly tray count can be adjusted with the farm.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: null,
    weeklyCapacity: null,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 30,
  },
  {
    id: "microgreens-sampler",
    name: "Microgreens Sampler",
    description: "A rotating mix of what is ready for the next harvest window.",
    priceCents: 1000,
    kind: "ONE_TIME",
    subscriptionInterval: null,
    leadTimeDays: 7,
    cutoffNote: "Rotating microgreens sampler.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: 40,
    weeklyCapacity: 40,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 100,
  },
  ...microgreenTrayProducts,
  {
    id: "blackberries",
    name: "Blackberries",
    description: "Fresh seasonal blackberries from the farm when the patch is producing.",
    priceCents: 0,
    kind: "ONE_TIME",
    subscriptionInterval: null,
    leadTimeDays: 1,
    cutoffNote: "Seasonal add-on when available.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: null,
    weeklyCapacity: null,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 220,
  },
  {
    id: "peppers",
    name: "Peppers",
    description: "Choose from our seasonal pepper varieties when the plants are producing.",
    priceCents: 0,
    kind: "ONE_TIME",
    subscriptionInterval: null,
    leadTimeDays: 1,
    cutoffNote: "Available as the pepper crop allows.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: null,
    weeklyCapacity: null,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 230,
  },
  {
    id: "fresh-lavender-bundle",
    name: "Fresh Lavender Bundle",
    description: "Fresh lavender bundles from Clark Dubignon Farms.",
    priceCents: 1000,
    kind: "ONE_TIME",
    subscriptionInterval: null,
    leadTimeDays: 2,
    cutoffNote: "Available seasonally while fresh cuts last.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: 25,
    weeklyCapacity: 25,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 240,
  },
  {
    id: "tomatoes",
    name: "Tomatoes",
    description: "Fresh tomatoes picked for local orders when the plants are producing.",
    priceCents: 0,
    kind: "ONE_TIME",
    subscriptionInterval: null,
    leadTimeDays: 1,
    cutoffNote: "Seasonal add-on when available.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: null,
    weeklyCapacity: null,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 250,
  },
  {
    id: "kale",
    name: "Kale",
    description: "Fresh farm kale available as a seasonal green when harvests allow.",
    priceCents: 0,
    kind: "ONE_TIME",
    subscriptionInterval: null,
    leadTimeDays: 1,
    cutoffNote: "Seasonal add-on when available.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: null,
    weeklyCapacity: null,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 260,
  },
  {
    id: "basil",
    name: "Basil",
    description: "Fresh farm basil available as a seasonal herb when the plants are producing.",
    priceCents: 0,
    kind: "ONE_TIME",
    subscriptionInterval: null,
    leadTimeDays: 1,
    cutoffNote: "Seasonal add-on when available.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: null,
    weeklyCapacity: null,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 270,
  },
  {
    id: "farm-eggs",
    name: "Farm Eggs",
    description: "Eggs from our laying flock, available for pickup when supply allows.",
    priceCents: 600,
    kind: "ONE_TIME",
    subscriptionInterval: null,
    leadTimeDays: 1,
    cutoffNote: "Pickup add-on when available.",
    isAvailable: true,
    isFeatured: false,
    stockQuantity: 40,
    weeklyCapacity: 40,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 280,
  },
  {
    id: "sugar-cane",
    name: "Sugar Cane",
    description: "Seasonal sugar cane from the farm, available in limited local batches.",
    priceCents: 0,
    kind: "ONE_TIME",
    subscriptionInterval: null,
    leadTimeDays: 1,
    cutoffNote: "Seasonal add-on when available.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: null,
    weeklyCapacity: null,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 290,
  },
  {
    id: "muscadines",
    name: "Muscadines",
    description: "Fresh muscadines when the vines are producing, sold as a seasonal pickup add-on.",
    priceCents: 0,
    kind: "ONE_TIME",
    subscriptionInterval: null,
    leadTimeDays: 1,
    cutoffNote: "Seasonal add-on when available.",
    isAvailable: true,
    isFeatured: true,
    stockQuantity: null,
    weeklyCapacity: null,
    fulfillmentMode: "PICKUP",
    imageUrl: null,
    imageS3Key: null,
    stripeProductId: null,
    stripePriceId: null,
    stripePriceAmountCents: null,
    sortOrder: 300,
  },
];
